name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.0'         
      - name: Install dependencies
        run: bundle install
      - name: Run Standard
        run: bundle exec standardrb
      - name: Run tests
        run: bundle exec rails test test/lib/generators/rails_mvp_authentication/install_generator_test.rb:11